# Name of workflow as seen in Github actions tab
name: deploy-model-prediction-front-end
# Run workflow only on push to dev branch
on:
  push:
    branches:
      - main

jobs:
  # To build the project
  build-front-end:
    runs-on: ubuntu-20.04
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Installing dependencies
        working-directory: ./react/price-prediction
        run: npm install
      - name: Building project
        working-directory: ./react/price-prediction
        run: npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
          ACL: "public-read"

      - name: Deploy to S3 bucket
        run: aws s3 sync ./react/price-prediction/build s3://stock-market-prediction-front-end --delete --acl public-read --exclude 'data/*'